### ISSUE TITLE
Merge with `cosmicjs-node` and make it universal?

### ISSUE THREAD

**Issue by iam4x** [cosmicjs/cosmicjs-browser#1]
Hello @tonyspiro,

I'm want to try cosmicjs and use it with https://github.com/iam4x/isomorphic-flux-boilerplate/ which does server/browser rendering of a ReactJS app.

For that I would need an universal library that can run on node and browser.

When I'll be granted beta access I can take care of that :+1: 

(Looking forward to try the product :100:  )

**Comment by tonyspiro** [comment]
Hey @iam4x, thanks for signing up for Cosmic JS during the private beta release!  You now have access and can sign in here: https://cosmicjs.com/login 

I agree that this should be a universal package, but hit a road block when trying to use the request package on the browser and haven't found a universal solution.  That's the only difference between the two.

cosmicjs-node uses [request](https://www.npmjs.com/package/request)
cosmicjs-browser uses [browser-request](https://www.npmjs.com/package/browser-request)

Maybe you can help me find a package that works on both the server and browser?

P.S. great work on the universal flux boilerplate :+1: !

**Comment by iam4x** [comment]
Hey @tonyspiro thank's for the invite :)

I will have fun with cosmicjs this weekend (girlfriend abroad) I will throw you a PR with an isomorphic library for fetching ;)

Cheers!

**Comment by tonyspiro** [comment]
Thanks @iam4x.  Enjoy and don't get into too much trouble with the gf away :beers:

**Comment by tonyspiro** [comment]
@iam4x [cosmicjs-node](https://github.com/cosmicjs/cosmicjs-node) package is now universal.
